recorder:
  db_url: mysql://agador:!password@192.168.0.49:3306/homeassistant?charset=utf8

homeassistant:
  name: Agador
  latitude: !latitude
  longitude: !longitude
  unit_system: imperial
  time_zone: America/New_York

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
