recorder:
  db_url: !secret recorder_db_url
  
homeassistant:
  name: Agador
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  time_zone: America/New_York
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
